# Generated by Django 4.1.10 on 2024-05-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IR', '0002_documentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='documentModel',
        ),
        migrations.AddField(
            model_name='searchenginemodel',
            name='relebant_document',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
