# Generated by Django 4.1.10 on 2024-05-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IR', '0003_delete_documentmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchenginemodel',
            name='relebant_document',
        ),
    ]
