# Generated by Django 4.1.10 on 2024-05-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IR', '0004_remove_searchenginemodel_relebant_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField()),
            ],
        ),
    ]
